# Southern Indiana Housing and Public School Analysis 
## Part 2

- In this notebook I will read in the ILEARN testing score data and clean it.

In [73]:
#Import necessary libraries and such for project. And some extra stuff, just in case.
import pandas as pd
import matplotlib
from pandas import DataFrame
import matplotlib.pyplot as plt
import numpy as np
import datetime

In [106]:
# read in the data for ILEARN 2024 test scores for all school coporations in Indiana - ELA section
ilearn_ELA_corp = pd.read_csv('Data_Sources\ILEARN_Corp_ELA.csv')

In [ ]:
# verify data reads in and print the first five rows)
ilearn_ELA_corp.head()

,Data Notes:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
0,Scores reflect all ILEARN Spring 2024 testers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,*** - Indicates less than 10 students in group...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Grade 3,NaN,NaN,NaN,NaN,NaN,NaN,Grade 4,...,NaN,NaN,Corporation Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Corp ID,Corp Name,ELA\nBelow\nProficiency,ELA \nApproaching\nProficiency,ELA \nAt\nProficiency,ELA \nAbove\nProficiency,ELA\nTotal\nProficient,ELA\nTotal\nTested,ELA\nProficient \n%,ELA\nBelow\nProficiency,...,ELA\nTotal\nTested,ELA\nProficient \n%,ELA\nBelow\nProficiency,ELA \nApproaching\nProficiency,ELA \nAt\nProficiency,ELA \nAbove\nProficiency,ELA\nTotal\nProficient,ELA\nTotal\nTested,ELA\nProficient \n%,NaN
4,0015,Adams Central Community Schools,35,21,24,9,33,89,37.1%,27,...,99,53.5%,168,139,180,108,288,595,48.4%,NaN

In [75]:
# will replace Nan value in dataframe with value 1
ela_copy = ilearn_ELA_corp.replace(to_replace = np.nan, value = 1)

for x in ela_copy.index:
    if ela_copy.loc[x, "Unnamed: 1"] == 1:
        ela_copy.drop(x, inplace=True)
ela_copy

,Data Notes:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
3,Corp ID,Corp Name,ELA\nBelow\nProficiency,ELA \nApproaching\nProficiency,ELA \nAt\nProficiency,ELA \nAbove\nProficiency,ELA\nTotal\nProficient,ELA\nTotal\nTested,ELA\nProficient \n%,ELA\nBelow\nProficiency,...,ELA\nTotal\nTested,ELA\nProficient \n%,ELA\nBelow\nProficiency,ELA \nApproaching\nProficiency,ELA \nAt\nProficiency,ELA \nAbove\nProficiency,ELA\nTotal\nProficient,ELA\nTotal\nTested,ELA\nProficient \n%,1.0
4,0015,Adams Central Community Schools,35,21,24,9,33,89,37.1%,27,...,99,53.5%,168,139,180,108,288,595,48.4%,1.0
5,0025,North Adams Community Schools,51,25,22,2,24,100,24.0%,31,...,98,44.9%,186,150,143,68,211,547,38.6%,1.0
6,0035,South Adams Schools,29,30,23,8,31,90,34.4%,29,...,88,54.5%,176,161,142,83,225,562,40.0%,1.0
7,0125,MSD Southwest Allen County Schls,135,110,157,144,301,546,55.1%,128,...,613,49.8%,803,833,1051,793,1844,3480,53.0%,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,9970,ACE Preparatory Academy,10,4,2,0,2,16,12.5%,8,...,1,1,27,15,11,2,13,55,23.6%,1.0
390,9975,Global Preparatory Academy,62,18,13,5,18,98,18.4%,26,...,37,16.2%,220,79,51,24,75,374,20.1%,1.0
391,9980,Steel City Academy,20,1,2,0,2,23,8.7%,17,...,23,34.8%,92,25,15,3,18,135,13.3%,1.0
392,9985,Seven Oaks Classical School,5,15,20,12,32,52,61.5%,3,...,26,65.4%,25,65,85,66,151,241,62.7%,1.0
393,9990,Higher Institute of Arts & Tech,20,5,1,0,1,26,3.8%,15,...,25,24.0%,81,42,19,4,23,146,15.8%,1.0

In [76]:
#find out datatype for Column 'Unnamed: 1'
print(ela_copy.dtypes)

#this is stupid. Let's rename the columns
# Renaming columns
ela_copy.rename(columns={'Data Notes:': 'Corp ID', 
                         'Unnamed: 1': 'Corp Name', 
                         'Unnamed: 2': 'ELA Below Proficiency', 
                         'Unnamed: 3': 'ELA Approaching Proficiency', 
                         'Unnamed: 4': 'ELA At Proficiency',
                         'Unnamed: 5': 'ELA Above Proficiency',
                         'Unnamed: 6': 'ELA Total Proficient',
                         'Unnamed: 7': 'ELA Total Tested',
                         'Unnamed: 8': 'ELA Proficient %',
                         }
                         , inplace=True)
print(ela_copy)

Data Notes:     object
Unnamed: 1      object
Unnamed: 2      object
Unnamed: 3      object
Unnamed: 4      object
Unnamed: 5      object
Unnamed: 6      object
Unnamed: 7      object
Unnamed: 8      object
Unnamed: 9      object
Unnamed: 10     object
Unnamed: 11     object
Unnamed: 12     object
Unnamed: 13     object
Unnamed: 14     object
Unnamed: 15     object
Unnamed: 16     object
Unnamed: 17     object
Unnamed: 18     object
Unnamed: 19     object
Unnamed: 20     object
Unnamed: 21     object
Unnamed: 22     object
Unnamed: 23     object
Unnamed: 24     object
Unnamed: 25     object
Unnamed: 26     object
Unnamed: 27     object
Unnamed: 28     object
Unnamed: 29     object
Unnamed: 30     object
Unnamed: 31     object
Unnamed: 32     object
Unnamed: 33     object
Unnamed: 34     object
Unnamed: 35     object
Unnamed: 36     object
Unnamed: 37     object
Unnamed: 38     object
Unnamed: 39     object
Unnamed: 40     object
Unnamed: 41     object
Unnamed: 42     object
Unnamed: 43     object
Unnamed: 44     object
Unnamed: 45     object
Unnamed: 46     object
Unnamed: 47     object
Unnamed: 48     object
Unnamed: 49     object
Unnamed: 50     object
Unnamed: 51    float64
dtype: object
     Corp ID                         Corp Name    ELA Below Proficiency  \
3    Corp ID                         Corp Name  ELA\nBelow\nProficiency
4       0015   Adams Central Community Schools                       35
5       0025     North Adams Community Schools                       51
6       0035               South Adams Schools                       29
7       0125  MSD Southwest Allen County Schls                      135
..       ...                               ...                      ...
389     9970           ACE Preparatory Academy                       10
390     9975        Global Preparatory Academy                       62
391     9980                Steel City Academy                       20
392     9985       Seven Oaks Classical School                        5
393     9990   Higher Institute of Arts & Tech                       20

        ELA Approaching Proficiency     ELA At Proficiency  \
3    ELA \nApproaching\nProficiency  ELA \nAt\nProficiency
4                                21                     24
5                                25                     22
6                                30                     23
7                               110                    157
..                              ...                    ...
389                               4                      2
390                              18                     13
391                               1                      2
392                              15                     20
393                               5                      1

        ELA Above Proficiency    ELA Total Proficient    ELA Total Tested  \
3    ELA \nAbove\nProficiency  ELA\nTotal\nProficient  ELA\nTotal\nTested
4                           9                      33                  89
5                           2                      24                 100
6                           8                      31                  90
7                         144                     301                 546
..                        ...                     ...                 ...
389                         0                       2                  16
390                         5                      18                  98
391                         0                       2                  23
392                        12                      32                  52
393                         0                       1                  26

        ELA Proficient %               Unnamed: 9  ...         Unnamed: 42  \
3    ELA\nProficient \n%  ELA\nBelow\nProficiency  ...  ELA\nTotal\nTested
4                  37.1%                       27  ...                  99
5                  24.0%                       31  ...                  98
6                  34.4%                       29  ...                  88
7                  55.1%                      128  ...                 613
..                   ...                      ...  ...                 ...
389                12.5%                        8  ...                   1
390                18.4%                       26  ...                  37
391                 8.7%                       17  ...                  23
392                61.5%                        3  ...                  26
393                 3.8%                       15  ...                  25

             Unnamed: 43              Unnamed: 44  \
3    ELA\nProficient \n%  ELA\nBelow\nProficiency
4                  53.5%                      168
5                  44.9%                      186
6                  54.5%                      176
7                  49.8%                      803
..                   ...                      ...
389                    1                       27
390                16.2%                      220
391                34.8%                       92
392                65.4%                       25
393                24.0%                       81

                        Unnamed: 45            Unnamed: 46  \
3    ELA \nApproaching\nProficiency  ELA \nAt\nProficiency
4                               139                    180
5                               150                    143
6                               161                    142
7                               833                   1051
..                              ...                    ...
389                              15                     11
390                              79                     51
391                              25                     15
392                              65                     85
393                              42                     19

                  Unnamed: 47             Unnamed: 48         Unnamed: 49  \
3    ELA \nAbove\nProficiency  ELA\nTotal\nProficient  ELA\nTotal\nTested
4                         108                     288                 595
5                          68                     211                 547
6                          83                     225                 562
7                         793                    1844                3480
..                        ...                     ...                 ...
389                         2                      13                  55
390                        24                      75                 374
391                         3                      18                 135
392                        66                     151                 241
393                         4                      23                 146

             Unnamed: 50 Unnamed: 51
3    ELA\nProficient \n%         1.0
4                  48.4%         1.0
5                  38.6%         1.0
6                  40.0%         1.0
7                  53.0%         1.0
..                   ...         ...
389                23.6%         1.0
390                20.1%         1.0
391                13.3%         1.0
392                62.7%         1.0
393                15.8%         1.0

[391 rows x 52 columns]

In [77]:
#drop rows 10 - 52 as I only want to focus on Grade 3 scores 
ela_copy2 = ela_copy.drop(ela_copy.iloc[:, 10:52], axis=1)

#dropping rows that are the final proficient %
ela_copy3 = ela_copy2.drop(labels=None, 
                         axis=1, 
                         columns=['ELA Below Proficiency', 
                                    'ELA Approaching Proficiency', 
                                    'ELA At Proficiency', 
                                    'ELA Above Proficiency',
                                    'ELA Total Proficient',
                                    'ELA Total Tested'], 
                        level=None, 
                        inplace=False, 
                        errors='raise')
ela_copy3

,Corp ID,Corp Name,ELA Proficient %,Unnamed: 9
3,Corp ID,Corp Name,ELA\nProficient \n%,ELA\nBelow\nProficiency
4,0015,Adams Central Community Schools,37.1%,27
5,0025,North Adams Community Schools,24.0%,31
6,0035,South Adams Schools,34.4%,29
7,0125,MSD Southwest Allen County Schls,55.1%,128
...,...,...,...,...
389,9970,ACE Preparatory Academy,12.5%,8
390,9975,Global Preparatory Academy,18.4%,26
391,9980,Steel City Academy,8.7%,17
392,9985,Seven Oaks Classical School,61.5%,3
393,9990,Higher Institute of Arts & Tech,3.8%,15

In [78]:
#dropping first row
#ela_copy.drop(index=ela_copy.index[0], axis=0, inplace=True)
#ela_copy

In [79]:
# List of school corporation state IDs
corps = ['1000', '1010', '0935', '0945', '2400']

# Filter DataFrame by list of school corporation state IDs
ela_copy3= ela_copy3[ela_copy3['Corp ID'].isin(corps)]
display(ela_copy3)

   Corp ID                             Corp Name ELA Proficient % Unnamed: 9
24    0935  Borden-Henryville School Corporation            30.9%         37
25    0945       Silver Creek School Corporation            41.7%         65
26    1000     Clarksville Community School Corp            13.7%        166
27    1010          Greater Clark County Schools            35.3%        303
64    2400           New Albany-Floyd Co Con Sch            55.8%        205

In [80]:
#read in the data for ILEARN 2024 test scores for all school coporations in Indiana - Math section

ilearn_Math_corp = pd.read_csv('Data_Sources\ILEARN_Corp_Math.csv')

In [81]:
# will replace Nan value in dataframe with value 1
math_copy = ilearn_Math_corp.replace(to_replace = np.nan, value = 1)

In [82]:
#change rows with NaN values to 1, drop from dataframe
for x in math_copy.index:
    if math_copy.loc[x, "Unnamed: 1"] == 1:
        math_copy.drop(x, inplace=True)
math_copy

,Data Notes:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
3,Corp ID,Corp Name,Math\nBelow\nProficiency,Math \nApproaching\nProficiency,Math \nAt\nProficiency,Math \nAbove\nProficiency,Math\nTotal\nProficient,Math\nTotal\nTested,Math\nProficient \n%,Math\nBelow\nProficiency,...,Math\nTotal\nTested,Math\nProficient \n%,Math\nBelow\nProficiency,Math \nApproaching\nProficiency,Math \nAt\nProficiency,Math \nAbove\nProficiency,Math\nTotal\nProficient,Math\nTotal\nTested,Math\nProficient \n%,1.0
4,0015,Adams Central Community Schools,16,17,39,17,56,89,62.9%,20,...,99,70.7%,107,124,191,173,364,595,61.2%,1.0
5,0025,North Adams Community Schools,28,27,32,13,45,100,45.0%,35,...,98,33.7%,205,155,133,52,185,545,33.9%,1.0
6,0035,South Adams Schools,20,16,32,22,54,90,60.0%,18,...,88,58.0%,126,143,161,132,293,562,52.1%,1.0
7,0125,MSD Southwest Allen County Schls,91,97,160,198,358,546,65.6%,116,...,612,47.4%,819,820,969,871,1840,3479,52.9%,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,9970,ACE Preparatory Academy,7,7,2,0,2,16,12.5%,7,...,1,1,22,18,12,3,15,55,27.3%,1.0
390,9975,Global Preparatory Academy,54,22,16,6,22,98,22.4%,28,...,37,8.1%,258,60,43,13,56,374,15.0%,1.0
391,9980,Steel City Academy,20,2,1,0,1,23,4.3%,19,...,23,17.4%,107,19,8,1,9,135,6.7%,1.0
392,9985,Seven Oaks Classical School,2,5,17,28,45,52,86.5%,0,...,26,50.0%,19,56,68,98,166,241,68.9%,1.0
393,9990,Higher Institute of Arts & Tech,20,3,3,0,3,26,11.5%,17,...,25,4.0%,110,24,10,2,12,146,8.2%,1.0

In [83]:
# Renaming column headers
math_copy.rename(columns={'Data Notes:': 'Corp ID', 
                         'Unnamed: 1': 'Corp Name', 
                         'Unnamed: 2': 'Math Below Proficiency', 
                         'Unnamed: 3': 'Math Approaching Proficiency', 
                         'Unnamed: 4': 'Math At Proficiency',
                         'Unnamed: 5': 'Math Above Proficiency',
                         'Unnamed: 6': 'Math Total Proficient',
                         'Unnamed: 7': 'Math Total Tested',
                         'Unnamed: 8': 'Math Proficient %',
                         }
                         , inplace=True)
display(math_copy)

,Corp ID,Corp Name,Math Below Proficiency,Math Approaching Proficiency,Math At Proficiency,Math Above Proficiency,Math Total Proficient,Math Total Tested,Math Proficient %,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
3,Corp ID,Corp Name,Math\nBelow\nProficiency,Math \nApproaching\nProficiency,Math \nAt\nProficiency,Math \nAbove\nProficiency,Math\nTotal\nProficient,Math\nTotal\nTested,Math\nProficient \n%,Math\nBelow\nProficiency,...,Math\nTotal\nTested,Math\nProficient \n%,Math\nBelow\nProficiency,Math \nApproaching\nProficiency,Math \nAt\nProficiency,Math \nAbove\nProficiency,Math\nTotal\nProficient,Math\nTotal\nTested,Math\nProficient \n%,1.0
4,0015,Adams Central Community Schools,16,17,39,17,56,89,62.9%,20,...,99,70.7%,107,124,191,173,364,595,61.2%,1.0
5,0025,North Adams Community Schools,28,27,32,13,45,100,45.0%,35,...,98,33.7%,205,155,133,52,185,545,33.9%,1.0
6,0035,South Adams Schools,20,16,32,22,54,90,60.0%,18,...,88,58.0%,126,143,161,132,293,562,52.1%,1.0
7,0125,MSD Southwest Allen County Schls,91,97,160,198,358,546,65.6%,116,...,612,47.4%,819,820,969,871,1840,3479,52.9%,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,9970,ACE Preparatory Academy,7,7,2,0,2,16,12.5%,7,...,1,1,22,18,12,3,15,55,27.3%,1.0
390,9975,Global Preparatory Academy,54,22,16,6,22,98,22.4%,28,...,37,8.1%,258,60,43,13,56,374,15.0%,1.0
391,9980,Steel City Academy,20,2,1,0,1,23,4.3%,19,...,23,17.4%,107,19,8,1,9,135,6.7%,1.0
392,9985,Seven Oaks Classical School,2,5,17,28,45,52,86.5%,0,...,26,50.0%,19,56,68,98,166,241,68.9%,1.0
393,9990,Higher Institute of Arts & Tech,20,3,3,0,3,26,11.5%,17,...,25,4.0%,110,24,10,2,12,146,8.2%,1.0

In [84]:
#dropping first row
math_copy.drop(index=math_copy.index[0], axis=0, inplace=True)
math_copy

,Corp ID,Corp Name,Math Below Proficiency,Math Approaching Proficiency,Math At Proficiency,Math Above Proficiency,Math Total Proficient,Math Total Tested,Math Proficient %,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
4,0015,Adams Central Community Schools,16,17,39,17,56,89,62.9%,20,...,99,70.7%,107,124,191,173,364,595,61.2%,1.0
5,0025,North Adams Community Schools,28,27,32,13,45,100,45.0%,35,...,98,33.7%,205,155,133,52,185,545,33.9%,1.0
6,0035,South Adams Schools,20,16,32,22,54,90,60.0%,18,...,88,58.0%,126,143,161,132,293,562,52.1%,1.0
7,0125,MSD Southwest Allen County Schls,91,97,160,198,358,546,65.6%,116,...,612,47.4%,819,820,969,871,1840,3479,52.9%,1.0
8,0225,Northwest Allen County Schools,102,103,232,155,387,592,65.4%,130,...,651,35.5%,931,1159,1148,660,1808,3898,46.4%,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,9970,ACE Preparatory Academy,7,7,2,0,2,16,12.5%,7,...,1,1,22,18,12,3,15,55,27.3%,1.0
390,9975,Global Preparatory Academy,54,22,16,6,22,98,22.4%,28,...,37,8.1%,258,60,43,13,56,374,15.0%,1.0
391,9980,Steel City Academy,20,2,1,0,1,23,4.3%,19,...,23,17.4%,107,19,8,1,9,135,6.7%,1.0
392,9985,Seven Oaks Classical School,2,5,17,28,45,52,86.5%,0,...,26,50.0%,19,56,68,98,166,241,68.9%,1.0
393,9990,Higher Institute of Arts & Tech,20,3,3,0,3,26,11.5%,17,...,25,4.0%,110,24,10,2,12,146,8.2%,1.0

In [85]:
#drop rows 10 - 52 as I only want to focus on Grade 3 scores 
math_copy2 = math_copy.drop(math_copy.iloc[:, 10:52], axis=1)

#dropping rows that are the final proficient %
math_copy3 = math_copy2.drop(labels=None, 
                         axis=1, 
                         columns=['Math Below Proficiency', 
                                    'Math Approaching Proficiency', 
                                    'Math At Proficiency', 
                                    'Math Above Proficiency',
                                    'Math Total Proficient',
                                    'Math Total Tested'], 
                        level=None, 
                        inplace=False, 
                        errors='raise')
math_copy3

    Corp ID                         Corp Name Math Proficient % Unnamed: 9
4      0015   Adams Central Community Schools             62.9%         20
5      0025     North Adams Community Schools             45.0%         35
6      0035               South Adams Schools             60.0%         18
7      0125  MSD Southwest Allen County Schls             65.6%        116
8      0225    Northwest Allen County Schools             65.4%        130
..      ...                               ...               ...        ...
389    9970           ACE Preparatory Academy             12.5%          7
390    9975        Global Preparatory Academy             22.4%         28
391    9980                Steel City Academy              4.3%         19
392    9985       Seven Oaks Classical School             86.5%          0
393    9990   Higher Institute of Arts & Tech             11.5%         17

[390 rows x 4 columns]

In [86]:
# List of school corporation state IDs
corps = ['1000', '1010', '0935', '0945', '2400']

# Filter DataFrame by list of school corporation state IDs
math_copy3= math_copy3[math_copy3['Corp ID'].isin(corps)]
display(math_copy3)

   Corp ID                             Corp Name Math Proficient % Unnamed: 9
24    0935  Borden-Henryville School Corporation             49.1%         40
25    0945       Silver Creek School Corporation             54.8%         76
26    1000     Clarksville Community School Corp             25.1%        188
27    1010          Greater Clark County Schools             47.1%        307
64    2400           New Albany-Floyd Co Con Sch             71.1%        178

In [87]:
# read in science data
ilearn_Science_corp = pd.read_csv('Data_Sources\ILEARN_Corp_Science.csv')

In [88]:
# will replace Nan value in dataframe with value 1
sci_copy = ilearn_Science_corp.replace(to_replace = np.nan, value = 1)

for x in sci_copy.index:
    if sci_copy.loc[x, "Unnamed: 1"] == 1:
        sci_copy.drop(x, inplace=True)
sci_copy

,Data Notes:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
3,Corp ID,Corp Name,Science\nBelow\nProficiency,Science \nApproaching\nProficiency,Science \nAt\nProficiency,Science \nAbove\nProficiency,Science\nTotal\nProficient,Science\nTotal\nTested,Science\nProficient \n%,Science\nBelow\nProficiency,...,Science\nTotal\nTested,Science\nProficient \n%,Science\nBelow\nProficiency,Science \nApproaching\nProficiency,Science \nAt\nProficiency,Science \nAbove\nProficiency,Science\nTotal\nProficient,Science\nTotal\nTested,Science\nProficient \n%,1.0
4,0015,Adams Central Community Schools,11,42,37,4,41,94,43.6%,11,...,111,62.2%,22,73,72,38,110,205,53.7%,1.0
5,0025,North Adams Community Schools,17,36,28,9,37,90,41.1%,15,...,82,35.4%,32,74,45,21,66,172,38.4%,1.0
6,0035,South Adams Schools,17,48,29,6,35,100,35.0%,18,...,100,45.0%,35,85,54,26,80,200,40.0%,1.0
7,0125,MSD Southwest Allen County Schls,65,178,205,90,295,538,54.8%,40,...,591,59.7%,105,376,345,303,648,1129,57.4%,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,9970,ACE Preparatory Academy,2,7,9,2,11,20,55.0%,1,...,1,1,2,7,9,2,11,20,55.0%,1.0
384,9975,Global Preparatory Academy,18,14,12,2,14,46,30.4%,37,...,70,10.0%,55,40,16,5,21,116,18.1%,1.0
385,9980,Steel City Academy,8,10,4,0,4,22,18.2%,14,...,28,7.1%,22,22,5,1,6,50,12.0%,1.0
386,9985,Seven Oaks Classical School,0,6,21,16,37,43,86.0%,2,...,33,54.5%,2,19,29,26,55,76,72.4%,1.0
387,9990,Higher Institute of Arts & Tech,12,9,1,2,3,24,12.5%,9,...,27,18.5%,21,22,5,3,8,51,15.7%,1.0

In [89]:
# Renaming columns
sci_copy.rename(columns={'Data Notes:': 'Corp ID', 
                         'Unnamed: 1': 'Corp Name', 
                         'Unnamed: 2': 'Science Below Proficiency', 
                         'Unnamed: 3': 'Science Approaching Proficiency', 
                         'Unnamed: 4': 'Science At Proficiency',
                         'Unnamed: 5': 'Science Above Proficiency',
                         'Unnamed: 6': 'Science Total Proficient',
                         'Unnamed: 7': 'Science Total Tested',
                         'Unnamed: 8': 'Science Proficient %',
                         }
                         , inplace=True)
display(sci_copy)

,Corp ID,Corp Name,Science Below Proficiency,Science Approaching Proficiency,Science At Proficiency,Science Above Proficiency,Science Total Proficient,Science Total Tested,Science Proficient %,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
3,Corp ID,Corp Name,Science\nBelow\nProficiency,Science \nApproaching\nProficiency,Science \nAt\nProficiency,Science \nAbove\nProficiency,Science\nTotal\nProficient,Science\nTotal\nTested,Science\nProficient \n%,Science\nBelow\nProficiency,...,Science\nTotal\nTested,Science\nProficient \n%,Science\nBelow\nProficiency,Science \nApproaching\nProficiency,Science \nAt\nProficiency,Science \nAbove\nProficiency,Science\nTotal\nProficient,Science\nTotal\nTested,Science\nProficient \n%,1.0
4,0015,Adams Central Community Schools,11,42,37,4,41,94,43.6%,11,...,111,62.2%,22,73,72,38,110,205,53.7%,1.0
5,0025,North Adams Community Schools,17,36,28,9,37,90,41.1%,15,...,82,35.4%,32,74,45,21,66,172,38.4%,1.0
6,0035,South Adams Schools,17,48,29,6,35,100,35.0%,18,...,100,45.0%,35,85,54,26,80,200,40.0%,1.0
7,0125,MSD Southwest Allen County Schls,65,178,205,90,295,538,54.8%,40,...,591,59.7%,105,376,345,303,648,1129,57.4%,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,9970,ACE Preparatory Academy,2,7,9,2,11,20,55.0%,1,...,1,1,2,7,9,2,11,20,55.0%,1.0
384,9975,Global Preparatory Academy,18,14,12,2,14,46,30.4%,37,...,70,10.0%,55,40,16,5,21,116,18.1%,1.0
385,9980,Steel City Academy,8,10,4,0,4,22,18.2%,14,...,28,7.1%,22,22,5,1,6,50,12.0%,1.0
386,9985,Seven Oaks Classical School,0,6,21,16,37,43,86.0%,2,...,33,54.5%,2,19,29,26,55,76,72.4%,1.0
387,9990,Higher Institute of Arts & Tech,12,9,1,2,3,24,12.5%,9,...,27,18.5%,21,22,5,3,8,51,15.7%,1.0

In [90]:
#dropping the columns that aren't for Grade 3
sci_copy = sci_copy.drop(sci_copy.iloc[:, 10:52], axis=1)
sci_copy

,Corp ID,Corp Name,Science Below Proficiency,Science Approaching Proficiency,Science At Proficiency,Science Above Proficiency,Science Total Proficient,Science Total Tested,Science Proficient %,Unnamed: 9
3,Corp ID,Corp Name,Science\nBelow\nProficiency,Science \nApproaching\nProficiency,Science \nAt\nProficiency,Science \nAbove\nProficiency,Science\nTotal\nProficient,Science\nTotal\nTested,Science\nProficient \n%,Science\nBelow\nProficiency
4,0015,Adams Central Community Schools,11,42,37,4,41,94,43.6%,11
5,0025,North Adams Community Schools,17,36,28,9,37,90,41.1%,15
6,0035,South Adams Schools,17,48,29,6,35,100,35.0%,18
7,0125,MSD Southwest Allen County Schls,65,178,205,90,295,538,54.8%,40
...,...,...,...,...,...,...,...,...,...,...
383,9970,ACE Preparatory Academy,2,7,9,2,11,20,55.0%,1
384,9975,Global Preparatory Academy,18,14,12,2,14,46,30.4%,37
385,9980,Steel City Academy,8,10,4,0,4,22,18.2%,14
386,9985,Seven Oaks Classical School,0,6,21,16,37,43,86.0%,2
387,9990,Higher Institute of Arts & Tech,12,9,1,2,3,24,12.5%,9

In [91]:
#dropping first row
sci_copy.drop(index=sci_copy.index[0], axis=0, inplace=True)
sci_copy

,Corp ID,Corp Name,Science Below Proficiency,Science Approaching Proficiency,Science At Proficiency,Science Above Proficiency,Science Total Proficient,Science Total Tested,Science Proficient %,Unnamed: 9
4,0015,Adams Central Community Schools,11,42,37,4,41,94,43.6%,11
5,0025,North Adams Community Schools,17,36,28,9,37,90,41.1%,15
6,0035,South Adams Schools,17,48,29,6,35,100,35.0%,18
7,0125,MSD Southwest Allen County Schls,65,178,205,90,295,538,54.8%,40
8,0225,Northwest Allen County Schools,59,239,261,95,356,654,54.4%,83
...,...,...,...,...,...,...,...,...,...,...
383,9970,ACE Preparatory Academy,2,7,9,2,11,20,55.0%,1
384,9975,Global Preparatory Academy,18,14,12,2,14,46,30.4%,37
385,9980,Steel City Academy,8,10,4,0,4,22,18.2%,14
386,9985,Seven Oaks Classical School,0,6,21,16,37,43,86.0%,2
387,9990,Higher Institute of Arts & Tech,12,9,1,2,3,24,12.5%,9

In [92]:
#drop rows 10 - 52 as I only want to focus on Grade 3 scores 
sci_copy2 = sci_copy.drop(sci_copy.iloc[:, 10:52], axis=1)

#dropping rows that are the final proficient %
sci_copy3 = sci_copy2.drop(labels=None, 
                         axis=1, 
                         columns=['Science Below Proficiency', 
                                    'Science Approaching Proficiency', 
                                    'Science At Proficiency', 
                                    'Science Above Proficiency',
                                    'Science Total Proficient',
                                    'Science Total Tested'], 
                        level=None, 
                        inplace=False, 
                        errors='raise')
sci_copy3

    Corp ID                         Corp Name Science Proficient % Unnamed: 9
4      0015   Adams Central Community Schools                43.6%         11
5      0025     North Adams Community Schools                41.1%         15
6      0035               South Adams Schools                35.0%         18
7      0125  MSD Southwest Allen County Schls                54.8%         40
8      0225    Northwest Allen County Schools                54.4%         83
..      ...                               ...                  ...        ...
383    9970           ACE Preparatory Academy                55.0%          1
384    9975        Global Preparatory Academy                30.4%         37
385    9980                Steel City Academy                18.2%         14
386    9985       Seven Oaks Classical School                86.0%          2
387    9990   Higher Institute of Arts & Tech                12.5%          9

[384 rows x 4 columns]

In [93]:
# List of school corporation state IDs
corps = ['1000', '1010', '0935', '0945', '2400']

# Filter DataFrame by list of school corporation state IDs
sci_copy3= sci_copy3[sci_copy3['Corp ID'].isin(corps)]
display(sci_copy3)

,Corp ID,Corp Name,Science Proficient %,Unnamed: 9
24,0935,Borden-Henryville School Corporation,49.6%,10
25,0945,Silver Creek School Corporation,41.5%,35
26,1000,Clarksville Community School Corp,20.6%,190
27,1010,Greater Clark County Schools,37.6%,176
64,2400,New Albany-Floyd Co Con Sch,49.1%,159

In [94]:
#read in social studies dataset
ilearn_Soc_corp = pd.read_csv('Data_Sources\ILEARN_Corp_SocSt.csv')

#look at first five rows and confirm there are NaN values in the top two rows
ilearn_Soc_corp.head(15)

,Data Notes:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Scores reflect all ILEARN Spring 2024 testers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,*** - Indicates less than 10 students in group...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Grade 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Corp ID,Corp Name,Social Studies\nBelow\nProficiency,Social Studies \nApproaching\nProficiency,Social Studies \nAt\nProficiency,Social Studies \nAbove\nProficiency,Social Studies\nTotal\nProficient,Social Studies\nTotal\nTested,Social Studies\nProficient \n%,NaN
4,0015,Adams Central Community Schools,38,25,24,15,39,102,38.2%,NaN
5,0025,North Adams Community Schools,29,22,20,11,31,82,37.8%,NaN
6,0035,South Adams Schools,32,19,22,17,39,90,43.3%,NaN
7,0125,MSD Southwest Allen County Schls,160,105,160,144,304,569,53.4%,NaN
8,0225,Northwest Allen County Schools,144,130,221,155,376,650,57.8%,NaN
9,0235,Fort Wayne Community Schools,1250,323,275,181,456,2029,22.5%,NaN
10,0255,East Allen County Schools,368,102,135,96,231,701,33.0%,NaN
11,0365,Bartholomew Con School Corp,390,159,161,112,273,822,33.2%,NaN
12,0370,Flat Rock-Hawcreek School Corp,43,23,13,5,18,84,21.4%,NaN
13,0395,Benton Community School Corp,39,19,26,18,44,102,43.1%,NaN
14,0515,Blackford County Schools,56,17,30,13,43,116,37.1%,NaN

Note: They only have scores for the Social Studies section for Grade 5. I'll need to keep this in mind when I merge the datasets for analysis.

In [95]:
# will replace Nan value in dataframe with value 1 and drop those rows
soc_copy = ilearn_Soc_corp.replace(to_replace = np.nan, value = 1)

for x in soc_copy.index:
    if soc_copy.loc[x, "Unnamed: 1"] == 1:
        soc_copy.drop(x, inplace=True)
soc_copy

,Data Notes:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
3,Corp ID,Corp Name,Social Studies\nBelow\nProficiency,Social Studies \nApproaching\nProficiency,Social Studies \nAt\nProficiency,Social Studies \nAbove\nProficiency,Social Studies\nTotal\nProficient,Social Studies\nTotal\nTested,Social Studies\nProficient \n%,1.0
4,0015,Adams Central Community Schools,38,25,24,15,39,102,38.2%,1.0
5,0025,North Adams Community Schools,29,22,20,11,31,82,37.8%,1.0
6,0035,South Adams Schools,32,19,22,17,39,90,43.3%,1.0
7,0125,MSD Southwest Allen County Schls,160,105,160,144,304,569,53.4%,1.0
...,...,...,...,...,...,...,...,...,...,...
374,9970,ACE Preparatory Academy,11,4,3,1,4,19,21.1%,1.0
375,9975,Global Preparatory Academy,44,12,4,0,4,60,6.7%,1.0
376,9980,Steel City Academy,23,2,0,0,0,25,0.0%,1.0
377,9985,Seven Oaks Classical School,7,6,9,19,28,41,68.3%,1.0
378,9990,Higher Institute of Arts & Tech,20,1,2,0,2,23,8.7%,1.0

In [96]:
# Renaming columns
soc_copy.rename(columns={'Data Notes:': 'Corp ID', 
                         'Unnamed: 1': 'Corp Name', 
                         'Unnamed: 2': 'Social Studies Below Proficiency', 
                         'Unnamed: 3': 'Social Studies Approaching Proficiency', 
                         'Unnamed: 4': 'Social Studies At Proficiency',
                         'Unnamed: 5': 'Social Studies Above Proficiency',
                         'Unnamed: 6': 'Social Studies Total Proficient',
                         'Unnamed: 7': 'Social Studies Total Tested',
                         'Unnamed: 8': 'Social Studies Proficient %',
                         }
                         , inplace=True)
display(soc_copy)

,Corp ID,Corp Name,Social Studies Below Proficiency,Social Studies Approaching Proficiency,Social Studies At Proficiency,Social Studies Above Proficiency,Social Studies Total Proficient,Social Studies Total Tested,Social Studies Proficient %,Unnamed: 9
3,Corp ID,Corp Name,Social Studies\nBelow\nProficiency,Social Studies \nApproaching\nProficiency,Social Studies \nAt\nProficiency,Social Studies \nAbove\nProficiency,Social Studies\nTotal\nProficient,Social Studies\nTotal\nTested,Social Studies\nProficient \n%,1.0
4,0015,Adams Central Community Schools,38,25,24,15,39,102,38.2%,1.0
5,0025,North Adams Community Schools,29,22,20,11,31,82,37.8%,1.0
6,0035,South Adams Schools,32,19,22,17,39,90,43.3%,1.0
7,0125,MSD Southwest Allen County Schls,160,105,160,144,304,569,53.4%,1.0
...,...,...,...,...,...,...,...,...,...,...
374,9970,ACE Preparatory Academy,11,4,3,1,4,19,21.1%,1.0
375,9975,Global Preparatory Academy,44,12,4,0,4,60,6.7%,1.0
376,9980,Steel City Academy,23,2,0,0,0,25,0.0%,1.0
377,9985,Seven Oaks Classical School,7,6,9,19,28,41,68.3%,1.0
378,9990,Higher Institute of Arts & Tech,20,1,2,0,2,23,8.7%,1.0

In [97]:
#dropping rows that are the final proficient %
soc_copy2 = soc_copy.drop(labels=None, 
                         axis=1, 
                         columns=['Social Studies Below Proficiency', 
                                    'Social Studies Approaching Proficiency', 
                                    'Social Studies At Proficiency', 
                                    'Social Studies Above Proficiency',
                                    'Social Studies Total Proficient',
                                    'Social Studies Total Tested'], 
                        level=None, 
                        inplace=False, 
                        errors='raise')
soc_copy2

,Corp ID,Corp Name,Social Studies Proficient %,Unnamed: 9
3,Corp ID,Corp Name,Social Studies\nProficient \n%,1.0
4,0015,Adams Central Community Schools,38.2%,1.0
5,0025,North Adams Community Schools,37.8%,1.0
6,0035,South Adams Schools,43.3%,1.0
7,0125,MSD Southwest Allen County Schls,53.4%,1.0
...,...,...,...,...
374,9970,ACE Preparatory Academy,21.1%,1.0
375,9975,Global Preparatory Academy,6.7%,1.0
376,9980,Steel City Academy,0.0%,1.0
377,9985,Seven Oaks Classical School,68.3%,1.0
378,9990,Higher Institute of Arts & Tech,8.7%,1.0

In [98]:
# List of school corporation state IDs
corps = ['1000', '1010', '0935', '0945', '2400']

# Filter DataFrame by list of school corporation state IDs
soc_copy2= soc_copy2[soc_copy2['Corp ID'].isin(corps)]
display(soc_copy2)

,Corp ID,Corp Name,Social Studies Proficient %,Unnamed: 9
24,0935,Borden-Henryville School Corporation,26.4%,1.0
25,0945,Silver Creek School Corporation,29.3%,1.0
26,1000,Clarksville Community School Corp,14.6%,1.0
27,1010,Greater Clark County Schools,28.4%,1.0
64,2400,New Albany-Floyd Co Con Sch,40.1%,1.0

In [99]:
#dropping the last column in soc_copy2 - unknown data
soc_copy3 = soc_copy2.drop(labels=None, 
                        axis=1, 
                        columns=['Unnamed: 9'], 
                        level=None, 
                        inplace=False, 
                        errors='raise').rename(columns={"Corp Name" : "Corporation Name"})

soc_copy3

   Corp ID                      Corporation Name Social Studies Proficient %
24    0935  Borden-Henryville School Corporation                       26.4%
25    0945       Silver Creek School Corporation                       29.3%
26    1000     Clarksville Community School Corp                       14.6%
27    1010          Greater Clark County Schools                       28.4%
64    2400           New Albany-Floyd Co Con Sch                       40.1%

In [100]:
#Merge ELA, Math, and Science results (all Grade 3)
# 1. Using merge(): Merge all DataFrames on 'Species' column
merged_df = pd.merge(ela_copy3, math_copy3, on='Corp ID', how='inner')
merged_df = pd.merge(merged_df, sci_copy3, on='Corp ID', how='inner')
merged_ilearnG3df = merged_df.drop(labels=None, 
                        axis=1, 
                        columns=['Unnamed: 9_x',
                                'Unnamed: 9_y',
                                'Unnamed: 9',
                                'Corp Name_y',
                                'Corp Name'], 
                        level=None, 
                        inplace=False, 
                        errors='raise').rename(columns={"Corp Name_x": "Corporation Name"})

#view merged dataframes
display(merged_ilearnG3df)

,Corp ID,Corporation Name,ELA Proficient %,Math Proficient %,Science Proficient %
0,0935,Borden-Henryville School Corporation,30.9%,49.1%,49.6%
1,0945,Silver Creek School Corporation,41.7%,54.8%,41.5%
2,1000,Clarksville Community School Corp,13.7%,25.1%,20.6%
3,1010,Greater Clark County Schools,35.3%,47.1%,37.6%
4,2400,New Albany-Floyd Co Con Sch,55.8%,71.1%,49.1%

In [101]:
reindexed_ilearnG3df = merged_ilearnG3df.set_index('Corporation Name')

In [102]:
t_ilearnG3 = reindexed_ilearnG3df.T  # or df2.transpose()
t_ilearnG3

Corporation Name,Borden-Henryville School Corporation,Silver Creek School Corporation,Clarksville Community School Corp,Greater Clark County Schools,New Albany-Floyd Co Con Sch
Corp ID,0935,0945,1000,1010,2400
ELA Proficient %,30.9%,41.7%,13.7%,35.3%,55.8%
Math Proficient %,49.1%,54.8%,25.1%,47.1%,71.1%
Science Proficient %,49.6%,41.5%,20.6%,37.6%,49.1%

In [103]:
#write filtered data to csv to use in another noteboook
reindexed_ilearnG3df.to_csv('ilearnG3df.csv')

In [104]:
#write filtered data to csv to use in another noteboook
t_ilearnG3.to_csv('t_ilearnG3.csv')

In [105]:
#write filtered data to csv to use in another noteboook
soc_copy3.to_csv('soc_copy3.csv')