In [1]:
#Import necessary libraries and such for project. And some extra stuff, just in case.
import pandas as pd
import matplotlib
from pandas import DataFrame
import matplotlib.pyplot as plt

In [2]:
#read in the data for median square footage by county starting with Bartholomew County, IN 

bartco_sqft = pd.read_csv('Data_Sources\med_sqft_bartco.csv')

#verify data reads in and print the first five rows)
bartco_sqft.head()

,Day of Year,Year of Period End,Period Begin,Period End,Median Pending Sqft Yoy (tooltip),Median Pending Sqft Yoy,Median Pending Sqft
0,1,2023,12/5/2022,1/1/2023,-10.90%,-11%,"1,802.10"
1,2,2022,12/6/2021,1/2/2022,8.30%,8%,"2,023"
2,5,2025,12/9/2024,1/5/2025,9.90%,10%,"1,771.70"
3,7,2024,12/11/2023,1/7/2024,-18.80%,-19%,"1,612.10"
4,8,2023,12/12/2022,1/8/2023,5.90%,6%,"1,986.10"

In [3]:
#read in the data for median square footage by county - Floyd County, IN

floco_sqft = pd.read_csv('Data_Sources\med_sqft_floco.csv')

#verify data reads in and print the first five rows)
floco_sqft.head()

,Day of Year,Year of Period End,Period Begin,Period End,Median Pending Sqft Yoy (tooltip),Median Pending Sqft Yoy,Median Pending Sqft
0,1,2023,12/5/2022,1/1/2023,-22.00%,-22%,"1,535.70"
1,2,2022,12/6/2021,1/2/2022,8.50%,9%,"1,969.80"
2,5,2025,12/9/2024,1/5/2025,-13.00%,-13%,"1,742.20"
3,7,2024,12/11/2023,1/7/2024,23.70%,24%,"2,002.70"
4,8,2023,12/12/2022,1/8/2023,-15.50%,-16%,"1,619.50"

In [4]:
#read in the data for median square footage by county - Clark County, IN

claco_sqft = pd.read_csv('Data_Sources\med_sqft_claco.csv')

#verify data reads in and print the first five rows)
claco_sqft.head()

,Day of Year,Year of Period End,Period Begin,Period End,Median Pending Sqft Yoy (tooltip),Median Pending Sqft Yoy,Median Pending Sqft
0,1,2023,12/5/2022,1/1/2023,9.00%,9%,"1,771"
1,2,2022,12/6/2021,1/2/2022,6.30%,6%,"1,625.10"
2,5,2025,12/9/2024,1/5/2025,3.30%,3%,"1,526"
3,7,2024,12/11/2023,1/7/2024,-7.30%,-7%,"1,477.30"
4,8,2023,12/12/2022,1/8/2023,-1.90%,-2%,"1,593.70"

In [5]:
#read in the data for median listed housing prices by county - Clark County, IN

claco_price = pd.read_csv('Data_Sources\med_price_clark.csv')

#verify data reads in and print the first five rows)
claco_price.head()

,Day of Year,Last Updated,Year of Period End,Period Begin,Period End,Median Sale Price Yoy (tooltip),Median Sale Price Yoy,Median Sale Price
0,1,2/5/2025 14:47,2023,12/5/2022,1/1/2023,2.94%,0.029364,"229,023.70"
1,2,2/5/2025 14:47,2022,12/6/2021,1/2/2022,13.41%,0.134071,"222,490.50"
2,5,2/5/2025 14:47,2025,12/9/2024,1/5/2025,-3.95%,-0.039493,"227,735"
3,7,2/5/2025 14:47,2024,12/11/2023,1/7/2024,0.50%,0.004980,"237,098.70"
4,8,2/5/2025 14:47,2023,12/12/2022,1/8/2023,7.42%,0.074197,"235,923.70"

In [6]:
#read in the data for median listed housing prices by county - Floyd County, IN
floco_price = pd.read_csv('Data_Sources\med_price_floco.csv')

#verify data reads in and print the first five rows)
floco_price.head()

,Day of Year,Last Updated,Year of Period End,Period Begin,Period End,Median Sale Price Yoy (tooltip),Median Sale Price Yoy,Median Sale Price
0,1,2/12/2025 14:46,2023,12/5/2022,1/1/2023,-10.69%,-0.106938,"219,950"
1,2,2/12/2025 14:46,2022,12/6/2021,1/2/2022,21.05%,0.210519,"246,287.50"
2,5,2/12/2025 14:46,2025,12/9/2024,1/5/2025,33.33%,0.333254,"315,981.20"
3,7,2/12/2025 14:46,2024,12/11/2023,1/7/2024,-2.18%,-0.021823,"237,000"
4,8,2/12/2025 14:46,2023,12/12/2022,1/8/2023,3.50%,0.035030,"242,287.50"

In [7]:
#read in the data for median listed housing prices by county - Bartholomew County, IN
bartco_price = pd.read_csv('Data_Sources\med_price_bartco.csv')

#verify data reads in and print the first five rows)
bartco_price.head()

,Day of Year,Last Updated,Year of Period End,Period Begin,Period End,Median Sale Price Yoy (tooltip),Median Sale Price Yoy,Median Sale Price
0,1,2/12/2025 14:46,2023,12/5/2022,1/1/2023,-2.89%,-0.028948,"227,687.50"
1,2,2/12/2025 14:46,2022,12/6/2021,1/2/2022,14.94%,0.149387,"234,475"
2,5,2/12/2025 14:46,2025,12/9/2024,1/5/2025,-1.58%,-0.015849,"247,562.50"
3,7,2/12/2025 14:46,2024,12/11/2023,1/7/2024,5.84%,0.058375,"251,549.30"
4,8,2/12/2025 14:46,2023,12/12/2022,1/8/2023,3.29%,0.032920,"237,675"

In [8]:
#read in the data for ILEARN 2024 test scores for all school coporations in Indiana - ELA section
ilearn_ELA_corp = pd.read_csv('Data_Sources\ILEARN_Corp_ELA.csv')

#verify data reads in and print the first five rows)
ilearn_ELA_corp.head()

,Data Notes:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
0,Scores reflect all ILEARN Spring 2024 testers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,*** - Indicates less than 10 students in group...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Grade 3,NaN,NaN,NaN,NaN,NaN,NaN,Grade 4,...,NaN,NaN,Corporation Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Corp ID,Corp Name,ELA\nBelow\nProficiency,ELA \nApproaching\nProficiency,ELA \nAt\nProficiency,ELA \nAbove\nProficiency,ELA\nTotal\nProficient,ELA\nTotal\nTested,ELA\nProficient \n%,ELA\nBelow\nProficiency,...,ELA\nTotal\nTested,ELA\nProficient \n%,ELA\nBelow\nProficiency,ELA \nApproaching\nProficiency,ELA \nAt\nProficiency,ELA \nAbove\nProficiency,ELA\nTotal\nProficient,ELA\nTotal\nTested,ELA\nProficient \n%,NaN
4,0015,Adams Central Community Schools,35,21,24,9,33,89,37.1%,27,...,99,53.5%,168,139,180,108,288,595,48.4%,NaN

In [ ]:
# Reading in the mother file with all housing data by county
housing_data = pd.read_csv('Data_Sources\county_market_tracker.tsv000', sep='\t')

housing_data.head()

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,...,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2015-04-01,2015-04-30,30,county,5,2550,f,"Bradley County, TN",NaN,Tennessee,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,"Cleveland, TN",17420.0,2025-02-10 14:21:52
1,2014-02-01,2014-02-28,30,county,5,1958,f,"Dutchess County, NY",NaN,New York,...,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,"Poughkeepsie, NY",39100.0,2025-02-10 14:21:52
2,2023-06-01,2023-06-30,30,county,5,1643,f,"Holt County, MO",NaN,Missouri,...,-0.333333,0.307692,0.141026,NaN,NaN,NaN,NaN,Missouri nonmetropolitan area,NaN,2025-02-10 14:21:52
3,2015-03-01,2015-03-31,30,county,5,1518,f,"Adams County, MS",NaN,Mississippi,...,0.181818,NaN,NaN,NaN,0.0,0.0,0.0,"Natchez, MS",35020.0,2025-02-10 14:21:52
4,2016-02-01,2016-02-29,30,county,5,806,f,"Washington County, IL",NaN,Illinois,...,0.400000,NaN,NaN,NaN,0.0,0.0,0.0,Illinois nonmetropolitan area,NaN,2025-02-10 14:21:52

In [11]:
# What are the columns? I thought I saw pricing per sqft. I need to list all the column names.
# Displaying the size and data types of our data
hdata_shape = housing_data.shape
print(f'The DataFrame has {hdata_shape[0]} rows and {hdata_shape[1]} columns! \n')
print(housing_data.info())

The DataFrame has 1208726 rows and 58 columns!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1208726 entries, 0 to 1208725
Data columns (total 58 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   period_begin                    1208726 non-null  object
 1   period_end                      1208726 non-null  object
 2   period_duration                 1208726 non-null  int64
 3   region_type                     1208726 non-null  object
 4   region_type_id                  1208726 non-null  int64
 5   table_id                        1208726 non-null  int64
 6   is_seasonally_adjusted          1208726 non-null  object
 7   region                          1208726 non-null  object
 8   city                            0 non-null        float64
 9   state                           1208726 non-null  object
 10  state_code                      1208726 non-null  object
 11  property_type                   1208726 non-null  object
 12  property_type_id                1208726 non-null  int64
 13  median_sale_price               1207708 non-null  float64
 14  median_sale_price_mom           1088894 non-null  float64
 15  median_sale_price_yoy           1058296 non-null  float64
 16  median_list_price               1110721 non-null  float64
 17  median_list_price_mom           1022663 non-null  float64
 18  median_list_price_yoy           991936 non-null   float64
 19  median_ppsf                     1196024 non-null  float64
 20  median_ppsf_mom                 1078688 non-null  float64
 21  median_ppsf_yoy                 1048043 non-null  float64
 22  median_list_ppsf                1109384 non-null  float64
 23  median_list_ppsf_mom            1021205 non-null  float64
 24  median_list_ppsf_yoy            990412 non-null   float64
 25  homes_sold                      1207730 non-null  float64
 26  homes_sold_mom                  1088920 non-null  float64
 27  homes_sold_yoy                  1058318 non-null  float64
 28  pending_sales                   1153153 non-null  float64
 29  pending_sales_mom               1046064 non-null  float64
 30  pending_sales_yoy               1014868 non-null  float64
 31  new_listings                    1106035 non-null  float64
 32  new_listings_mom                1018260 non-null  float64
 33  new_listings_yoy                987257 non-null   float64
 34  inventory                       1164094 non-null  float64
 35  inventory_mom                   1066095 non-null  float64
 36  inventory_yoy                   1031661 non-null  float64
 37  months_of_supply                1177579 non-null  float64
 38  months_of_supply_mom            1078993 non-null  float64
 39  months_of_supply_yoy            1045431 non-null  float64
 40  median_dom                      1197265 non-null  float64
 41  median_dom_mom                  1078508 non-null  float64
 42  median_dom_yoy                  1047271 non-null  float64
 43  avg_sale_to_list                1115079 non-null  float64
 44  avg_sale_to_list_mom            1002595 non-null  float64
 45  avg_sale_to_list_yoy            975578 non-null   float64
 46  sold_above_list                 1201465 non-null  float64
 47  sold_above_list_mom             1082938 non-null  float64
 48  sold_above_list_yoy             1052271 non-null  float64
 49  price_drops                     581654 non-null   float64
 50  price_drops_mom                 529828 non-null   float64
 51  price_drops_yoy                 461129 non-null   float64
 52  off_market_in_two_weeks         1172079 non-null  float64
 53  off_market_in_two_weeks_mom     1063799 non-null  float64
 54  off_market_in_two_weeks_yoy     1031662 non-null  float64
 55  parent_metro_region             1208408 non-null  object
 56  parent_metro_region_metro_code  868682 non-null   float64
 57  last_updated                    1208726 non-null  object
dtypes: float64(44), int64(4), object(10)
memory usage: 534.9+ MB
None

''' 
The median pricing per square foot is located in column 19. 
'''